### ISSUE TITLE
having problem 

### ISSUE THREAD

**Issue by bediljan** [Marauders-9998/Attendance-Management-using-Face-Recognition#7]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "E:\new\new\Attendance-Management-using-Face-Recognition-master\Attendance_app.py", line 212, in doWork
    current_class_obj.capture_and_mark()
  File "E:\new\new\Attendance-Management-using-Face-Recognition-master\main_file.py", line 36, in capture_and_mark
    captured_image, frame = capture()
  File "E:\new\new\Attendance-Management-using-Face-Recognition-master\capture.py", line 34, in capture
    cv2.imshow("Click your picture", frame)
cv2.error: C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:331: error: (-215) size.width>0 && size.height>0 in function cv::imshow

**Comment by bediljan** [comment]
when inputing the username and password of new batch and train the recognizer is not working

**Comment by Vibhu-Agarwal** [comment]
@bediljan Please explain the exact steps to reproduce the bug.

**Comment by bediljan** [comment]
> @bediljan Please explain the exact steps to reproduce the bug.
> Also, mention:
> 
> * OS you're working on.
> * Version of Python you're using.
> * Libraries installed in your python environment.
....................
when i am successfully creating the batch or class, numbering the students from the student portal and then clicking on manager portal so the camera is not getting on to take pictures.

python version is 3.6
OS Windows 10
libraries which are linstalled are following

astroid                  1.6.3
CacheControl             0.12.4
cachetools               2.0.1
capture                  0.1
certifi                  2018.1.18
chardet                  3.0.4
colorama                 0.3.9
cycler                   0.10.0
django                   2.0.4
et-xmlfile               1.0.1
excel                    1.0.0
firebase-admin           2.10.0
google-api-core          1.1.0
google-auth              1.4.1
google-cloud-core        0.28.1
google-cloud-firestore   0.29.0
google-cloud-storage     1.8.0
google-resumable-media   0.3.1
googleapis-common-protos 1.5.3
idna                     2.6
imshow                   0.0.3
isort                    4.3.4
jdcal                    1.4
kiwisolver               1.0.1
lazy-object-proxy        1.3.1
matplotlib               2.2.2
mccabe                   0.6.1
mp3play                  0.1.15
msgpack-python           0.5.6
numpy                    1.14.2
opencv-contrib-python    3.4.0.12
opencv-python            3.4.1
openpyxl                 2.6.2
Pillow                   5.1.0
pip                      10.0.0
playsound                1.2.2
protobuf                 3.5.2.post1
pyasn1                   0.4.2
pyasn1-modules           0.2.1
PyAutoGUI                0.9.42
PyGetWindow              0.0.4
pylint                   1.8.4
PyMsgBox                 1.0.6
pyparsing                2.2.0
PyQt5                    5.12.1
PyQt5-sip                4.19.15
PyRect                   0.1.4
PyScreeze                0.1.20
python-dateutil          2.7.2
PyTweening               1.0.3
pytz                     2018.4
requests                 2.18.4
rsa                      3.4.2
scipy                    1.2.1
setuptools               39.0.1
sip                      4.19.8
six                      1.11.0
Theano                   1.0.4
urllib3                  1.22
workbook                 1.1
wrapt                    1.10.11
xlrd                     1.1.0
xlutils                  2.0.0
xlwt                     1.3.0

**Comment by Vibhu-Agarwal** [comment]
Try again after changing the parameter values [0, 1, 2, ...] over here:
https://github.com/Marauders-9998/Attendance-Management-using-Face-Recognition/blob/462956d9c787cca2175d0853c17f4ef902cffe02/capture.py#L27
